### ISSUE TITLE
ArrayObject access a bit too strict

### ISSUE THREAD

**Issue by dereuromark** [rectorphp/type-perfect#27]
```php
    /**
     * @param \Cake\Event\EventInterface $event
     * @param \ArrayObject<string, mixed> $data
     * @param \ArrayObject<string, mixed> $options
     *
     * @return void
     */
    public function beforeMarshal(EventInterface $event, ArrayObject $data, ArrayObject $options): void
    {
        if (isset($data['password']) && $data['password'] === '') {
            unset($data['password']);
        }
    }
```

From framework perspective this is the only way to work with it.
I would not expect the errors here then, if I typehinted it as `\ArrayObject<string, mixed>` instead of just `\ArrayObject` etc:

>   Use explicit methods over array access on object    
>   Use explicit methods over array access on object

**Comment by TomasVotruba** [comment]
I see. What do you suggest?

**Comment by dereuromark** [comment]
It should only alert for normal `\ArrayObject` annotation. Once you specify that it is expected to be used as assoc array, it should not alert anymore. Would make it possible to be used for us at least like this.

**Comment by TomasVotruba** [comment]
I see. I'm out of time for this package,
so if you need such feature, please provide a patch 👍
