### ISSUE TITLE
NarrowPublicClassMethodParamTypeRule: Don't suggest array types

### ISSUE THREAD

**Issue by staabm** [rectorphp/type-perfect#34]
I think the rule is going too far, when suggesting phpdoc-array types for a method which is already typed as a native array type

we get errors like
```
 ------ --------------------------------------------------------------------------------------------------------------------
  Line   kunzmann\app\shared\models\Land.php
 ------ --------------------------------------------------------------------------------------------------------------------
  106    Land->getListArray: Parameters should have "array<string, int>" types as the only types passed to this method
  118    Land->getListArrayNames: Parameters should have "array<string, int>" types as the only types passed to this method
 ------ --------------------------------------------------------------------------------------------------------------------
```

for our methods

```
class Land
{
    public function getListArray(array $con = []): array
    {
    }

    public function getListArrayNames(array $con = []): array
    {
    }
}
```

and because arrays are used a lot in php projects, these errors flood the phpstan reporting, so way more interessting errors can easily be overlooked.

wdyt about making the rule happy, when a parameter is already natively array-typed?

**Comment by staabm** [comment]
I also had a case where the rule error was

> Parameters should have \"array\\|array\" types as the only types passed to this method

and I don't understand what the error is trying to tell me.
maybe there is some kind of overlap with https://github.com/rectorphp/type-perfect/issues/35

**Comment by TomasVotruba** [comment]
Failing test fixture PR is needed 👍

**Comment by staabm** [comment]
test-case in https://github.com/rectorphp/type-perfect/pull/38

**Comment by TomasVotruba** [comment]
Going through stale issues and closing "the  ideas" one to keep focus on PRs and change.
Feel free to propose a PR with a fix/feature :+1: 

Thanks for understanding
