### ISSUE TITLE
NarrowPublicClassMethodParamTypeRule: error message too generic

### ISSUE THREAD

**Issue by staabm** [rectorphp/type-perfect#35]
in some situations we get errors like

> Parameters should have "float" types as the only types passed to this method

working with these errors after they got baselined is pretty hard, as the error message does not contain enough context.

suggestions
- mention the actual method name, not just "this method"

**Comment by scollovati** [comment]
The error message should report the parameter(s) name that should be removed. As of now it reports something like `Parameters should have "string" types as the only types passed to this method ` when the second argument can be removed since it is unused.

**Comment by TomasVotruba** [comment]
Going through stale issues and closing "the  ideas" one to keep focus on PRs and change.
Feel free to propose a PR :+1: 

Thanks for understanding
