### ISSUE TITLE
release downgrade failed

### ISSUE THREAD

**Issue by staabm** [rectorphp/type-perfect#45]
I think it looks like that the latest 1.0.0 release PHP downgrade failed

https://github.com/rectorphp/type-perfect/actions/runs/11128835212

**Comment by staabm** [comment]
hmm maybe this was repaired in the meantime. I am not sure, just stumbled over this error in the github actions tab

**Comment by samsonasik** [comment]
It looks like duplicated process, as it tries to re-downgrade already released version. The downgrade release already there, so should be no longer another downgrade process, it maybe due to downgrade process target on same repository.
