### ISSUE TITLE
New major version of PHPStan

### ISSUE THREAD

**Issue by dbublik** [rectorphp/type-perfect#47]
Hello!
Thanks for your work and for this package!

PHPStan has released a new major version - https://github.com/phpstan/phpstan/releases/tag/2.0.0
Could you update your package to support this version?

**Comment by TomasVotruba** [comment]
Hey,

that's great news 👌 
Not sure when we get to it, but PR is welcomed 👍

**Comment by staabm** [comment]
a PHPStan 2.x compatible version was released. this issue can be closed
