### ISSUE TITLE
Enum cases reported

### ISSUE THREAD

**Issue by janedbal** [rectorphp/type-perfect#8]
When only single enum case is passed, it gets reported. That is obviously not possible to typehint:

```txt
Parameter 4 should use "ShipMonk\Warehouse\PickToLight\Enum\SkipPickReason::BarcodeIssue" type as the only type passed to this method 
```

**Comment by samsonasik** [comment]
@janedbal could you give more precise code when it shown the error? thank you.

**Comment by janedbal** [comment]
Method

```php
    public function skipPick(
        SkipPickReason $skipPickReason,
    ): void
```

called only with `SkipPickReason::BarcodeIssue` of


```php
enum SkipPickReason: string
{

    case BarcodeIssue = 'barcode_issue';
    case EmptyLocation = 'empty_location';

}
```

**Comment by samsonasik** [comment]
@janedbal I can't reproduce issue by this PR test

- https://github.com/rectorphp/type-perfect/pull/19

 could you verify if something missing in the test? Thank you.

**Comment by samsonasik** [comment]
Closing as can't be reproduced, @janedbal feel free to create valid failing test case PR when you have time. thank you.

**Comment by samsonasik** [comment]
Re-open as reproduced at https://github.com/rectorphp/type-perfect/pull/19
