### ISSUE TITLE
callable reported when more specific Closure is used

### ISSUE THREAD

**Issue by janedbal** [rectorphp/type-perfect#9]
Using `narrow_param: true`, method looks like this:

```php
public function map(Closure $mapper): array
```

And get wrongly reported with wider suggestion:

```
Parameters should have "callable" types as the only types passed to this method
```

**Comment by samsonasik** [comment]
@janedbal could you give more precise code when it shown the error? thank you.

**Comment by janedbal** [comment]
The map method is called only with Closures. But it gets reported to be changed to `callable`, which is more wider type than used.

```php
$object->map(function () {});
```

**Comment by samsonasik** [comment]
It seems between `Closure` and `callable` make flip flop in case of this check removed:

https://github.com/rectorphp/type-perfect/blob/df83404dda3364cae1b4f5251420f95ef20fa493/src/Printer/CollectorMetadataPrinter.php#L177-L179

then, create a method with `callable` method:

```php
final class SkipCallable
{
    public function map(callable $mapper): array
    {
        return [];
    }

    public function run()
    {
        $this->map(function () {});
    }
}
```

then become error:

```php
+'09: Parameters should have "Closure" types as the only types passed to this method
```
